%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) (equal for both cameras after stereo rectification)
Camera.fx: 640.590088 #748.35791
Camera.fy: 640.183533 #748.35791
Camera.cx: 637.286316 #446.621033 
Camera.cy: 402.818481 #245.689011 

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30 #15.0

# stereo baseline times fx
Camera.bf: 31.9337001166 #11.6935675766 TranslationLeftRight: -49.8504437 -0.109076 0.017740
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 120.0 # 35

# Transformation from camera 0 to body-frame (imu) !!!!!!!!!!!!!!!!!!!!!!!!
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]
   #data: [ -5.7586305857286746e-03, -4.0463318787729019e-03,
   #      9.9997523237933461e-01, 2.0329267950355900e-02,
   #      -9.9998287214160420e-01, -1.0224590553211677e-03,
   #      -5.7628118925283633e-03, 7.9325209639615653e-03,
   #      1.0457519809151661e-03, -9.9999129084997906e-01,
   #      -4.0403746097850135e-03, 2.8559824645148020e-03, 0., 0., 0., 1. ]
   
   #data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
   #      0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
   #     -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
   #      0.0, 0.0, 0.0, 1.0]

# IMU noise (altered)
IMU.NoiseGyro: 1.6968e-04 #0.01 # 1.6968e-04 
IMU.NoiseAcc: 2.0000e-3 #0.1 # 2.0000e-3
IMU.GyroWalk: 0.0001 #0.0001 
IMU.AccWalk: 3.0000e-3 #0.001 # 3.0000e-3
IMU.Frequency: 100

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 480 
LEFT.width: 640
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   #data: [0.253336, 0.499059, -0.000710, -0.000385, 0.000000]
   data: [-0.055629, 0.063853, -0.000203, 0.000965, -0.020792]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [640.590088, 0.0, 637.286316, 0.0, 640.183533, 402.818481, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix #??????? 
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
LEFT.Rf:  !!opencv-matrix #???????
   rows: 3
   cols: 3
   dt: f
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [640.590088, 0.0, 637.286316, 0.0, 0.0, 640.183533, 402.818481, 0.0, 0.0, 0.0, 1.0, 0.0]

RIGHT.height: 480
RIGHT.width: 640
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.056637, 0.067119, -0.000290, -0.001725, -0.022515]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [642.577454, 0.0, 648.905396, 0.0, 642.286743, 406.992188, 0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.999985, -0.002579, -0.004907,  0.002565, 0.999993,  -0.002864, 0.004915, 0.002851, 0.999984]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [642.577454, 0.0, 648.905396, -49.8504437,  0.0, 642.286743, 406.992188, -0.109076, 0.0, 0.0, 1.0, 0.017740]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 10 
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.005
Viewer.KeyFrameLineWidth: 0.1
Viewer.GraphLineWidth: 5
Viewer.PointSize: 1
Viewer.CameraSize: 0.02
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

